name: deploy flight-booking-demo
on:
  push:
    branches:
      - main
    paths:
      - "demos/flight-booking-demo/config/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://speechly/cli:latest
        with:
          args: deploy -a ${{ secrets.APPID_FLIGHT_BOOKING_DEMO }} demos/flight-booking-demo/config -w
        env:
          SPEECHLY_APIKEY: ${{ secrets.SPEECHLY_APIKEY }}
