name: deploy voice-picking
on:
  push:
    branches:
      - main
    paths:
      - "demos/voice-picking/config/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://speechly/cli:latest
        with:
          args: deploy -a ${{ secrets.APPID_VOICE_PICKING }} demos/voice-picking/config -w
        env:
          SPEECHLY_APIKEY: ${{ secrets.SPEECHLY_APIKEY }}
