name: deploy speech-to-text
on:
  push:
    branches:
      - main
    paths:
      - "demos/speech-to-text/config/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://speechly/cli:latest
        with:
          args: deploy -a ${{ secrets.APPID_SPEECH_TO_TEXT }} demos/speech-to-text/config -w
        env:
          SPEECHLY_APIKEY: ${{ secrets.SPEECHLY_APIKEY }}
