name: 'PR build'

on:
  pull_request:
    branches:
      - 'main'
      - 'release/**'

env:
  WEBPACK_MODE: prd
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 25
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: common/temp/pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('common/config/rush/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.20.0
      - name: Setup Node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '14'
      - name: Check change log update
        run: node common/scripts/install-run-rush.js change --target-branch origin/main --verify
      - name: Install Dependencies
        run: node common/scripts/install-run-rush.js install --no-link
      - name: Link dependencies
        run: node common/scripts/install-run-rush.js link
      - name: Build Project
        run: node common/scripts/install-run-rush.js rebuild --verbose
